# Generated by Django 3.2.9 on 2022-03-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('organisationNumber', models.IntegerField()),
                ('avatar', models.CharField(max_length=100)),
                ('phoneNumber', models.IntegerField()),
                ('isSuperviser', models.BooleanField()),
            ],
        ),
    ]
