# Generated by Django 3.2.9 on 2022-03-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_avatarimages_chat_eventimages_events_organisations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organisations',
            new_name='Organizations',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.RenameField(
            model_name='avatarimages',
            old_name='avatarImage',
            new_name='avatar_image',
        ),
        migrations.RenameField(
            model_name='eventimages',
            old_name='eventImage',
            new_name='event_image',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='reportedUser',
            new_name='reported_user',
        ),
        migrations.RenameField(
            model_name='organizations',
            old_name='organisationNumber',
            new_name='organization_number',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='isSuperviser',
            new_name='is_supervisor',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='organisationNumber',
            new_name='organization_number',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='user_name',
        ),
    ]
