# Generated by Django 3.2.9 on 2022-03-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_organizations_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventImages',
            new_name='AvatarImage',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='AvatarImages',
            new_name='EventImage',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='avatarimage',
            old_name='event_image',
            new_name='avatar_image',
        ),
        migrations.RenameField(
            model_name='eventimage',
            old_name='avatar_image',
            new_name='event_image',
        ),
    ]
